# Generated by Django 5.0.3 on 2024-05-02 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_rename_descritption_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eCommerce.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('gr', 'gr'), ('Kg', 'Kg'), ('ml', 'ml'), ('Lt', 'Lt'), ('Cope', 'Cope')], max_length=10, null=True),
        ),
    ]
